### ISSUE TITLE
CMAKE_CXX_STANDARD

### ISSUE THREAD

**Issue by synthMoza** [timattt/RedArchiever#10]
https://github.com/timattt/RedArchiever/blob/6a8c969e3410f0c54d7c3f19f23355e0f3bace2c/CMakeLists.txt#L7
Но вы же пишете на C, почему вы выставляете стандарт C++? Тогда уж ```set(CMAKE_C_STANDARD 98)```

**Comment by timattt** [comment]
@DenRen 
ты писал cmake
