### ISSUE TITLE
Wrong cmake_minimum_required

### ISSUE THREAD

**Issue by synthMoza** [timattt/RedArchiever#5]
https://github.com/timattt/RedArchiever/blob/d9cdfbe4c505d9aaa924e8a5e3e7b07282fdd235/CMakeLists.txt#L1

Что есть такого в этом CMakeLists.txt, что при версиях ниже 3.13 падаем с FATAL_ERROR?

**Comment by timattt** [comment]
Это просто копипаста из другого проекта.
Писать самому скрипты сборки - не царское дело.
Но поправить, конечно смысл есть.
Было бы здорово сделать pull request.

**Comment by synthMoza** [comment]
> Писать самому скрипты сборки - не царское дело.

Писать хороший скрипт сборки - залог хорошего проекта.

> Было бы здорово сделать pull request.

Т.к. прямого участия в проекте я не планирую, могу только посоветовать хотя бы что-то типо:
```
cmake_minimum_required(VERSION 3.13)
project(archieve)

set(SRC_DIR source)
set(INCLUDE_DIR include)

set(SOURCE ${SRC_DIR}/... ${SRC_DIR}/... ${SRC_DIR}/...)

add_executable(${PROJECT_NAME} ${SRC_DIR})
target_include_directory(${PROJECT_NAME} PRIVATE ${INCLUDE_DIR})
```

**Comment by timattt** [comment]
Мне нравится твой лаконичный стиль комментариев.
Про царское дело была шутка, конечно же.
