### ISSUE TITLE
C/C++ mix

### ISSUE THREAD

**Issue by synthMoza** [timattt/RedArchiever#6]
https://github.com/timattt/RedArchiever/blob/d9cdfbe4c505d9aaa924e8a5e3e7b07282fdd235/Sources/Archiever.cpp#L3

Почему src - void*, а dest - void*&? Почему не void**?
Зачем передавать srcSizeBytes по значению, а destSizeBytes по ссылке?

Не только здесь, но и в функциях unarchive, encrypt/decrypt. Кстати, слово unarchive очень странное, скорее pack/unpack

**Comment by timattt** [comment]
1. Берем из c++ нужное. Но вообще реализация вдохновлена кодом из [этой](http://e-maxx.ru/algo/treap) древней статьи.
2. Потому что зачем. Указатель ничего не весит. Так что разницы считай никакой.
3. Оно странное, но зато точно не вводит в заблуждение.

**Comment by synthMoza** [comment]
Ну, won't fix так won't fix. Мне видится интерфейс так:
 `ssize_t pack(const void* src, size_t srcSizeBytes, void** dest)` - возвращаем размер dest, либо ошибку (см. signed size_t)
