### ISSUE TITLE
long int/int implicit cast

### ISSUE THREAD

**Issue by synthMoza** [timattt/RedArchiever#7]
https://github.com/timattt/RedArchiever/blob/d9cdfbe4c505d9aaa924e8a5e3e7b07282fdd235/Sources/Core.cpp#L16

Почему размер получаем как long, а возвращаем int? Потенциальная потеря данных в неявном приведении типа

**Comment by timattt** [comment]
Реально. Если файл больше 2ГБ, то все поломается
Исправим

**Comment by timattt** [comment]
Забили хрен.
Поставили ограничение по размерам на 1ГБ

**Comment by DenRen** [comment]
> А смысл архивировать такие маленькие данные?)

А смысл писать архиватор для больших файлов? Tакой уже есть :D

**Comment by synthMoza** [comment]
С такой логикой возникает очевидный вопрос...

> > А смысл архивировать такие маленькие данные?)
> 
> А смысл писать архиватор для больших файлов? Tакой уже есть :D
