### ISSUE TITLE
fwrite/fread ignore return

### ISSUE THREAD

**Issue by synthMoza** [timattt/RedArchiever#8]
https://github.com/timattt/RedArchiever/blob/d9cdfbe4c505d9aaa924e8a5e3e7b07282fdd235/Sources/Core.cpp#L45

Нет проверки, что написали/прочитали столько, сколько дали в функцию.

**Comment by timattt** [comment]
по факту, исправим

**Comment by timattt** [comment]
done

**Comment by synthMoza** [comment]
Раз пишите на Си, надо возвращать ошибку из функции, а не просто ее логировать, тем более функция возвращает сейчас void
